import sys
import os


def create_one_device(name: str):
    print("Creating structure for", name)

    print("mkdir =>", name)
    os.mkdir(name)
    print("chdir =>", name)
    os.chdir(name)

    # Create common recovery/-> recovery/ symlink
    def symlink(src: str, dest: str):
        print(f"symlink {src} => {dest}")
        os.symlink(src, dest)

    symlink("../exynos7885-common/recovery", "recovery")

    def create_and_write(filename: str, content: str):
        print(f"Creating {filename}")
        with open(filename, "w") as f:
            f.write(f"# Generated by {__file__}")
            f.write(content)

        # Create product makefile
    create_and_write(
            f"twrp_{name}.mk",
            f"""
$(call inherit-product, device/samsung/exynos7885-common/twrp_common.mk)

## Device identifier. This must come after all inclusions
PRODUCT_NAME := twrp_{name}
PRODUCT_DEVICE := {name}
PRODUCT_MODEL := Galaxy {name.capitalize()}""",
        )

    create_and_write(
        f"BoardConfig.mk",
        f"""
include device/samsung/exynos7885-common/BoardConfigCommon.mk
""",
    )

    create_and_write(
        "AndroidProducts.mk",
        f"""
PRODUCT_MAKEFILES := $(LOCAL_DIR)/twrp_{name}.mk
""",
    )
    print("chdir =>", "..")
    os.chdir('..')


def main():
    if len(sys.argv) < 2:
        print("Usage: python create_twrp_device.py <device_names>...")
        sys.exit(1)

    for device in sys.argv[1:]:
        create_one_device(device)


if __name__ == "__main__":
    main()
