# Generated by /home/royna/TWRP/device/samsung/a30/generate_device.py
$(call inherit-product, device/samsung/exynos7885-common/twrp_common.mk)

## Device identifier. This must come after all inclusions
PRODUCT_NAME := twrp_a20
PRODUCT_DEVICE := a20
PRODUCT_MODEL := Galaxy A20